# Generated by Django 2.1 on 2020-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('price_change', models.FloatField(blank=True, null=True)),
                ('p_change', models.FloatField(blank=True, null=True)),
                ('ma5', models.FloatField(blank=True, null=True)),
                ('ma10', models.FloatField(blank=True, null=True)),
                ('ma20', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'share_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'share_sort',
                'managed': False,
            },
        ),
    ]
